import textwrap
from pathlib import Path

import pytest

from promptprobe.schema import Case, Suite, SuiteValidationError, load_suite

FIXTURES = Path(__file__).parent / "fixtures"


def test_load_valid_suite():
    suite = load_suite(FIXTURES / "valid_suite.yaml")
    assert suite.name == "translation-quality"
    assert suite.scorer == "contains"
    assert len(suite.cases) == 2
    assert suite.cases[0].id == "case_0"
    assert suite.cases[1].id == "farewell-case"


def test_default_temperature(tmp_path):
    f = tmp_path / "suite.yaml"
    f.write_text(textwrap.dedent("""\
        name: t
        system_prompt: p
        model: m
        scorer: exact
        cases:
          - user: hi
            expected: hello
    """))
    suite = load_suite(f)
    assert suite.temperature == 0.0
    assert isinstance(suite.temperature, float)


def test_case_id_autogenerated(tmp_path):
    f = tmp_path / "suite.yaml"
    f.write_text(textwrap.dedent("""\
        name: t
        system_prompt: p
        model: m
        scorer: exact
        cases:
          - user: a
            expected: b
          - user: c
            expected: d
    """))
    suite = load_suite(f)
    assert suite.cases[0].id == "case_0"
    assert suite.cases[1].id == "case_1"


@pytest.mark.parametrize("missing_key", ["name", "system_prompt", "model", "scorer", "cases"])
def test_missing_required_field(tmp_path, missing_key):
    base = {
        "name": "t",
        "system_prompt": "p",
        "model": "m",
        "scorer": "exact",
        "cases": [{"user": "hi", "expected": "hello"}],
    }
    base.pop(missing_key)
    lines = "\n".join(f"{k}: {v!r}" for k, v in base.items() if not isinstance(v, list))
    if "cases" in base:
        lines += "\ncases:\n  - user: hi\n    expected: hello"
    f = tmp_path / "suite.yaml"
    f.write_text(lines)
    with pytest.raises(SuiteValidationError) as exc_info:
        load_suite(f)
    assert missing_key in str(exc_info.value)


def test_invalid_scorer(tmp_path):
    f = tmp_path / "suite.yaml"
    f.write_text(textwrap.dedent("""\
        name: t
        system_prompt: p
        model: m
        scorer: banana
        cases:
          - user: hi
            expected: hello
    """))
    with pytest.raises(SuiteValidationError) as exc_info:
        load_suite(f)
    assert "banana" in str(exc_info.value)


def test_empty_cases_list(tmp_path):
    f = tmp_path / "suite.yaml"
    f.write_text(textwrap.dedent("""\
        name: t
        system_prompt: p
        model: m
        scorer: exact
        cases: []
    """))
    with pytest.raises(SuiteValidationError):
        load_suite(f)


def test_case_missing_user(tmp_path):
    f = tmp_path / "suite.yaml"
    f.write_text(textwrap.dedent("""\
        name: t
        system_prompt: p
        model: m
        scorer: exact
        cases:
          - expected: hello
    """))
    with pytest.raises(SuiteValidationError) as exc_info:
        load_suite(f)
    assert "cases[0]" in str(exc_info.value)
    assert "user" in str(exc_info.value)


def test_case_missing_expected(tmp_path):
    f = tmp_path / "suite.yaml"
    f.write_text(textwrap.dedent("""\
        name: t
        system_prompt: p
        model: m
        scorer: exact
        cases:
          - user: hi
    """))
    with pytest.raises(SuiteValidationError) as exc_info:
        load_suite(f)
    assert "cases[0]" in str(exc_info.value)
    assert "expected" in str(exc_info.value)


def test_invalid_yaml(tmp_path):
    f = tmp_path / "bad.yaml"
    f.write_text(": bad: [yaml")
    with pytest.raises(SuiteValidationError) as exc_info:
        load_suite(f)
    assert str(exc_info.value).startswith("Invalid YAML")


def test_missing_scorer_fixture():
    with pytest.raises(SuiteValidationError) as exc_info:
        load_suite(FIXTURES / "missing_scorer.yaml")
    assert "scorer" in str(exc_info.value)
